# Mapping intra-camp droite : conserve uniquement la droite et l'extrÃªme droite
mapping:
  droite: droite
  droite_moderee: droite
  right: droite
  exdroite: exdroite
  far_right: exdroite

unknown_labels:
  policy: drop
  other_label: other
